# Generated by Django 5.1.7 on 2025-03-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_sblawat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsblawat',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Polubienia'),
        ),
        migrations.AddField(
            model_name='postsblawat',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Wyświetlenia'),
        ),
        migrations.AlterField(
            model_name='postsblawat',
            name='content',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='postsblawat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='postsblawat',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('tresc', models.TextField(verbose_name='Treść komentarza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='blog_sblawat.postsblawat')),
            ],
        ),
    ]
